### ISSUE TITLE
Error reading from database when a table has a column that is a reserved word

### ISSUE THREAD

**Issue by lmscloud-io** [lmscloud-io/moodle-tool_vault#7]
```
Error reading from database (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'usermodified,timecreated,timemodified,count FROM mdl_local_wunderbyte_table O...' at line 1
SELECT id,hash,tablehash,idstring,userid,page,jsonstring,sql,usermodified,timecreated,timemodified,count 
FROM mdl_local_wunderbyte_table ORDER BY id
[array (
)])

#0 /var/www/lib/dml/moodle_read_slave_trait.php(293): moodle_database->query_end(false)
#1 /var/www/lib/dml/mysqli_native_moodle_database.php(1337): mysqli_native_moodle_database->query_end(false)
#2 /var/www/lib/dml/moodle_database.php(1406): mysqli_native_moodle_database->get_recordset_sql('SELECT id,hash,...', Array, 0, 0)
#3 /var/www/admin/tool/vault/classes/site_backup.php(317): moodle_database->get_recordset_select('local_wunderbyt...', '', Array, 'id', 'id,hash,tableha...', 0, 0)
#4 /var/www/admin/tool/vault/classes/site_backup.php(387): tool_vault\site_backup->export_table_data(Object(tool_vault\local\xmldb\dbtable), '/var/www/...')
#5 /var/www/admin/tool/vault/classes/site_backup.php(225): tool_vault\site_backup->export_db()
#6 /var/www/admin/tool/vault/classes/task/cron_task.php(198): tool_vault\site_backup->execute()
#7 /var/www/admin/tool/vault/classes/task/cron_task.php(144): tool_vault\task\cron_task->start_operation(Object(tool_vault\local\models\backup_model))
#8 /var/www/lib/classes/cron.php(405): tool_vault\task\cron_task->execute()
#9 /var/www/lib/classes/cron.php(208): core\cron::run_inner_scheduled_task(Object(tool_vault\task\cron_task))
#10 /var/www/lib/classes/cron.php(125): core\cron::run_scheduled_tasks(1711613882, 1711613882)
#11 /var/www/admin/cron.php(80): core\cron::run_main_process(0)
#12 {main}
```

**Comment by lmscloud-io** [comment]
Fixed in v1.4
